// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Rockmusic_Videos ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IRockmusic_VideosViewModel
    {		
	    /// <summary>
        /// IsInternetAvalaible property.
        /// </summary>		
        Visibility IsInternetAvalaible { get; }
        /// <summary>
        /// Gets/Sets the Rockmusic_VideosListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.YouTubeVideo> Rockmusic_VideosListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Rockmusic_VideosListControlCollectionPageNumber property.
        /// </summary>
		int Rockmusic_VideosListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedRockmusic_VideosListControlCollection property.
        /// </summary>
		EntitiesBase.YouTubeVideo SelectedRockmusic_VideosListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedMenuSection_MenuMenuControl property.
        /// </summary>
		Controls.MenuItemData SelectedMenuSection_MenuMenuControl { get; set; }
        
        /// <summary>
        /// Gets the RefreshRockmusic_VideosListControlCollectionCommand command.
        /// </summary>
		ICommand RefreshRockmusic_VideosListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetRockmusic_VideosListControlCollectionCommand command.
        /// </summary>
		ICommand GetRockmusic_VideosListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
