// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Rockmusic_DetailVideos ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IRockmusic_DetailVideosViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentYouTubeVideo property.
        /// </summary>
		EntitiesBase.YouTubeVideo CurrentYouTubeVideo { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaRockmusic_DetailVideos0 property.
        /// </summary>
		bool HasNextpanoramaRockmusic_DetailVideos0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaRockmusic_DetailVideos0 property.
        /// </summary>
		bool HasPreviouspanoramaRockmusic_DetailVideos0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechRockmusic_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechRockmusic_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareRockmusic_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand ShareRockmusic_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartRockmusic_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand PinToStartRockmusic_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceRockmusic_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceRockmusic_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaRockmusic_DetailVideos0 command.
        /// </summary>
		ICommand NextpanoramaRockmusic_DetailVideos0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaRockmusic_DetailVideos0 command.
        /// </summary>
		ICommand PreviouspanoramaRockmusic_DetailVideos0 { get; }

	}
}
